# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #000000
background         #FFFFEA
cursor             #000000

active_tab_foreground     #FFFFEA
active_tab_background     #000000
inactive_tab_foreground   #000000
inactive_tab_background   #FFFFEA

active_border_color   #000000
inactive_border_color #FFFFEA
bell_border_color     #303030

color0      #101010
color1		#303030
color2		#CCCC7C
color3		#FFFFCA
color4		#EAFFFF
color5		#505050
color6		#AEEEEE
color7		#FCFCCE
color8		#101010
color9		#303030
color10		#CCCC7C
color11		#FFFFCA
color12		#EAFFFF
color13		#505050
color14		#AEEEEE
color15		#FCFCCE
