# Custom user keybinds
bind = Super+Alt, A, exec, "/home/light/Antigravity IDE/antigravity-ide"

# Layer rules for WhiteSur-style nwg-dock
layerrule = blur true, match:namespace nwg-dock
layerrule = ignore_alpha 0.2, match:namespace nwg-dock

